### ISSUE TITLE
Cancelling file selection

### ISSUE THREAD

**Issue by siniradam** [br14n-sol/inquirer-file-selector#2]
There is no cancel option.
`ESC` key could be used for cancelling the selection and `Backspace` for parent folder.

**Comment by br14n-sol** [comment]
I'm not sure I understand what you mean by cancelling the selection 😅

**Comment by siniradam** [comment]
Sure, let me try, once you trigger fileselection, you have to pick something, you can't cancel the operation for istance;

```js
const filePath = await fileSelector({
  message: 'Select a file:',
  onCancel:()=>{
   doSomethingOrPreviousMenu()
  }
})
```

I'm working on a shell tool, usually there are menus, their sub menus, and user can go back to previous menu.
At one point if you trigger file selection, then change your mind, you're stuck. 
Have to terminate the app and start from the beginning all over again.

**Comment by br14n-sol** [comment]
I guess you want to do something like this: [Inquirer.js/demo/index.mjs](https://github.com/SBoudrias/Inquirer.js/blob/main/packages/demo/index.mjs#L63)
Only instead of being an option in the file list, make it a "signal" when the `Esc` key is pressed.

It should be simple to implement, I'm just not sure about using the `Backspace` key to do the navigation between directories, since I was planning at some point to include a small search like you would do with [@inquirer/search](https://github.com/SBoudrias/Inquirer.js/tree/main/packages/search) useful for searching files in long lists.

**Comment by siniradam** [comment]
If recall correctly ‘Backspace’ button is being used for going back in (Windows) file explorer, also use to used for “Go Back” in browsers, AFAIK chrome abandoned this but there are chrome extensions to provide this feature again.

Feels like ‘Backspace’ is natural for going back and ‘Esc’ for exiting.

**Comment by br14n-sol** [comment]
honestly you are right it is the most natural thing to do, for the moment I could do it this way, when I want to do the search I will think of something.
